### ISSUE TITLE
Generating a Go structure in the plural

### ISSUE THREAD

**Issue by FlymeDllVa** [go-jet/jet#105]
I make a users table in the database, run a generator, it generates a model for me `type Users struct {}`, I would like `type User struct {}`

At the same time, leave users in the table package

If the number was not pure, it would allow, for example, to make beautiful documentation in GraphGQL, and in general it seems struct is about 1 object.

Let's say [sqlc](https://sqlc.dev/) is done exactly as I describe

**Comment by go-jet** [comment]
To customize generator: https://github.com/go-jet/jet/wiki/Generator#generator-customization

**Comment by FlymeDllVa** [comment]
Using the generator, I renamed the model from the users table. (model.User => model.User), while I did not touch the table.

The request comes out as expected
```sql
SELECT users.id AS "users.id",
FROM schema.users
```

But when trying to execute QueryContext, it is not possible to do a Scan correctly
For a correct scan to the new structure, you need to rename the SQL generation or add db tags to the structure
```sql
SELECT users.id AS "user.id",
FROM schema.users
```

Which solution is considered correct?

**Comment by go-jet** [comment]
Because you've changed model type name, default scan mapping `table_name.column_name` => `model_type_name.field_name` does not work. 
To make it work, you'll need to overwrite default mapping. 
This can be done by:
1)  adding `alias` tag for each of the model fields. For instance: ```ID `alias:"users.id"` ```
Tag can be added automatically with generator customization([test example](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/tests/postgres/generator_template_test.go#L287)). 
2) adding tag on a wrapped model type: 
  ```go
    type User struct {
          model.User `alias:"users.*"`
    }
  ```
More info about aliasing: https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#tagging-model-type-fields.

**Comment by FlymeDllVa** [comment]
Is it possible to do without wrapping the model only by means of a generator? In general, even with wrapping, I could not repeat your example.

**Comment by go-jet** [comment]
Yeah, you don't need to wrap a model if you generator is doing the aliasing. It's first or the second approach.  
Could you share you generator code, and a statement?

**Comment by FlymeDllVa** [comment]
Everything is OK, I found a problem. Thank you so much for your help!
