### ISSUE TITLE
Print Full SQL Instead of PreparedStatement

### ISSUE THREAD

**Issue by driverpt** [go-jet/jet#128]
**Is your feature request related to a problem? Please describe.**
Currently we are using RDS Data API which has a very specific way of doing queries (Doesn't support `?` character).

We required to either have named placeholders (each prefixed by `:`) and typed arguments, or we just call `ExecuteStatement` with the fully generated and escaped SQL.

Connecting directly via Connection String is not an option because we are using AWS Lambda.

[Source](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.calling)

**Describe the solution you'd like**
A `.RawSql()` Function that prints the whole SQL

**Comment by go-jet** [comment]
Hi @driverpt. `.DebugSql()` will return SQL without parameters.

**Comment by driverpt** [comment]
Will it he pretty printed? I'm asking because some of the queries are a bit big and there is a 1 MB Limit

**Comment by go-jet** [comment]
`DebugSql` will return valid sql. You can see sample [here](https://github.com/go-jet/jet#lets-write-some-sql-queries-in-go) or in [tests](https://github.com/go-jet/jet/tree/master/tests/mysql).

But, note that `DebugSql` is not intended to be used on the production, because of the possible SQL injection attacks.
If I were you, I would probably use `.Sql()` and replace each occurrence of `?` with some generated name `:gen_name` in the query.

**Comment by driverpt** [comment]
We could do what, but wouldn't it be a bit costly in long queries?

AWS RDS Data Api is nice, but it requires a lot of custom code.

Is there some way of creating a custom adapter for JET? To generate the query to Execute Statement Endpoint?

**Comment by go-jet** [comment]
How big are the queries? 1MB?

You can also fork the repo and update [ArgumentPlaceholder](https://github.com/go-jet/jet/blob/c29f0afd2bbc8364d6f1d46be24d1e4decb39616/mysql/dialect.go#L26) function -  
`return ":var_" + strconv.Itoa(ord)`. 
Or maybe update the code so that this function can be updated on startup.

> Is there some way of creating a custom adapter for JET? To generate the query to Execute Statement Endpoint?

Not sure what you mean? 
Do you mean adapter for query generation (`.Sql()`)? Should be answered with above comment.
Or do you mean do adapt `.Exec` or `.Query` methods? No, there is no such possibility.

**Comment by driverpt** [comment]
Can you make these configurable when we're initializing Jet?

Can you modify the `ArgumentPlaceholder` Function to also receive the Parameter Name ?

Thanks in advance

**Comment by go-jet** [comment]
I think it is the best, for you to fork the project and make necessary changes. Additional changes will probably be needed, because this data source is not supported currently.
