### ISSUE TITLE
Does Jet support QueryRow?

### ISSUE THREAD

**Issue by duchiporexia** [go-jet/jet#20]
Does Jet support QueryRow for only one row.

**Comment by duchiporexia** [comment]
@go-jet Great!
But in Go sql, "Query" doesn't return  sql.ErrNoRows, although "QueryRow" does. 

So, probably, we need two versions: error and no error for different use cases. 

For those who are familiar to Go sql, it is better to add an extra QueryRow function instead of returning an error in "Query into struct", which seems confusing to them.

**Comment by go-jet** [comment]
More appropriate name for Jet `Query` would be `QueryResultMapping`. Because it does 3 things beneath. It calls "database/sql" `Query`, then it calls `Scan` on each row and maps each row scan result into destination. The idea behind Jet `Query` method wasn't to wrap just "database/sql" `Query` but to wrap those 3 steps and thus speed up the development. 

Also neither "database/sql" `Query` or `QueryRow` returns sql.ErrNoRows. Only each Row's Scan will return ErrNoRows if row is empty.

Even if there is a separate method in Jet, that will query into struct, it wouldn't be called `QueryRow`, it would be probably called something like `QueryOne`, because multiple rows can be scanned into one struct destination, if that struct destination contains slices. If the struct destination does not contain slices than this imaginary `QueryOne` method would behave as `QueryRow`.  
All this is already a part of jet `Query`(of course sql.ErrNoRows is now missing).

If the idea behind new `QueryRow` method is to have access to `sql.Row` and manually call `Scan` then developer can use statement `Sql()` method to get raw sql with arguments as described above.
This can be achieved with only one additional line of code.

**Comment by duchiporexia** [comment]
@go-jet Yes, you are right. Jet should use another query (QueryOne or QueryResultMapping) to return the error ErrNoRows, not in Query.

**Comment by duchiporexia** [comment]
@go-jet Good. Make sense. Thanks.
