### ISSUE TITLE
Support for reading from schema file instead of dsn

### ISSUE THREAD

**Issue by NamLH1310** [go-jet/jet#271]
I am running to a case where I cannot access to dsn due to ACL. Therefore, reading the schema from a file would be nice.

**Comment by houten11** [comment]
What stops you from spinning up the local dev environment?

**Comment by amanbolat** [comment]
@houten11 What you are requesting seems to be out of scope of this library. Generating the code from an SQL Schema file requires parsing the file.

However, you already have schema, why not just spin up local docker and generate code from there?

**Comment by qazwsxedckll** [comment]
@go-jet  It is because the dsn is changing so the command cannot be stored in Makefile or scripts and I have to teach other people how to use the command many times.

**Comment by go-jet** [comment]
Hi @qazwsxedckll. I assume `dsn` is changing because there is no local development set up. Lack of local development is a such bad practice, and adding a new feature to jet just to support such a practice is out of the question.  
Also, see this discussion for more info https://github.com/go-jet/jet/discussions/150, https://github.com/go-jet/jet/discussions/165.
