### ISSUE TITLE
Efficient combination of jet and gRPC

### ISSUE THREAD

**Issue by jamesthegiantpeach** [go-jet/jet#31]
Thanks for this great repo.

I'm wondering what the best way to use this repo is with gRPC. I have some proto messages that will be stored in some PG tables, and i'm wondering what the most efficient way to use jet would be in such a situation. Is it possible for me to unpack query results directly into structs generated via gRPC?

Here's an example struct and its associated proto message:

generated:
```
type Dataset struct {
	// A server generated ID that is unique across the system.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Dataset
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The account ID that this Dataset belongs to.
	AccountId string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// This is the time the Dataset was created, in seconds from the epoch.
	CreateTime           *time.Time `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3,stdtime" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}
```

proto message:
```
message Dataset {
    // A server generated ID that is unique across the system.
    string id = 1;

    // The name of the Dataset
    string name = 2;

    // The account ID that this Dataset belongs to.
    string account_id = 3;

    // This is the time the Dataset was created, in seconds from the epoch.
    google.protobuf.Timestamp create_time = 4 [(gogoproto.stdtime) = true];

}
```

To me, it seems like the only real option is to treat model.Dataset that Jet generates as a storage layer, and have functions that cast between model.Dataset and the Dataset struct that gRPC generates. 

Any thoughts?

**Comment by go-jet** [comment]
Hi @jamesthegiantpeach,
It is possible to unpack the result of the query directly into gRPC struct, or any other struct, as long as it follows the rules for the custom model types: https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#custom-model-files. Meaning the name of the struct should correspond to the database table name, the name of the field should correspond to the column name, and column values are assignable to the struct field.
If your destination is a flat struct(meaning does not contain slices of other structs) you don't have to set `sql:"primary_key"` tag.
If you destination is not flat, you will have to set `sql:"primary_key"` tag, so that QRM knows how to unpack the result. It seems that protobuf does not have ability to set custom tag, but I see there are some libraries that enables this feature.

**Comment by jamesthegiantpeach** [comment]
Thanks for this.

The protobuf struct has extra fields that are used by gRPC. When unpacking, will jet ignore these and simply unpack into the fields that match columns?

**Comment by go-jet** [comment]
Yes, jet will ignore unmatched fields.

**Comment by jamesthegiantpeach** [comment]
Great! Thanks for the clarification.
