### ISSUE TITLE
Make aliasing function name consistent for Expression and ColumnList

### ISSUE THREAD

**Issue by jamius19** [go-jet/jet#422]
**Is your feature request related to a problem? Please describe.**
Jet is amazing, but it kind of bugs me to see that the aliasing function is named differently depending on whether I'm selecting one column or multiple columns. In my opinion it's a bit confusing, and when I first started using Jet, I though I might be using the wrong API function.

For example,

1. **For Individual Columns (from the `expression.go:24:Expression` interface):** `AS()`
2. **For ColumnList (from the `column_list.go:46:ColumnList` type):** `As()`

This snippet ought to highlight the issue I'm talking about,
```go
sqlite.
SELECT(
	table.Person.Name.AS("full_name"),
	table.Pet.AllColumns.As("pets"),
).
FROM(
	// ... omitted for brevity
)
```

\
**Describe the solution you'd like**
I would very much like to see both of these aliasing functions having same name. The names should not collide with each other since they're from different places.
```go
sqlite.
SELECT(
	table.Person.Name.AS("full_name"),
	table.Pet.AllColumns.AS("pets"),
).
FROM(
	// ... omitted for brevity
)
```

I know it'd be a breaking change, and probably not something everyone would want.
Just putting it out there for my piece of mind!

Have a great day!

**Comment by go-jet** [comment]
In general, the naming conventions are as follows (although there are exceptions):

* Uppercase methods: These map directly, one-to-one, to the corresponding SQL. For example, SELECT, FROM, WHERE, EQ, etc...
* CamelCase methods: These typically performs something extra. For instance, the `As` method generates a new projection list where table aliases are renamed. Since re-aliasing column lists is not a default SQL operation, it is CamelCase.

**Comment by jamius19** [comment]
That makes sense, thanks for your time!
