### ISSUE TITLE
Why is `SET()` not purely variadic?

### ISSUE THREAD

**Issue by gkdr** [go-jet/jet#52]
Hi again,

I have a question regarding the signature you chose on some functions.
For example, after using `UPDATE(columns ...jet.Column)`, you have to use `SET(value interface{}, values ...interface{})`. So in the first function, you can comfortably use a slice, but not in the second one. A similar case that comes to mind is `SELECT(projection Projection, projections ...Projection)`. Without digging too deep, I can't really tell why it needs to be like this. Could you explain?

(In my specific case, I had either one or two items in my slice. I tried `SET(vals[0], vals[1:]...)`, but (iirc) with only one item JET would complain that the lenghts of the parameter lists to the update and set clauses is different. If the interface needs to stay that way, maybe this is something that can be fixed instead.)

**Comment by go-jet** [comment]
The original idea was to prevent construction of invalid sql, but as you point out there is a problem if slices are passed. It is a part of public API so I hesitate to remove it until the next major release(unless there is no easy workaround).
There are workaround for your cases:
You can use `ProjectionList` for SELECT or RETURNING clause: [Example](https://github.com/go-jet/jet/wiki/FAQ#how-to-construct-dynamic-projection-list)
Note that UPDATE can have 3 forms (non type-safe SET, type-safe SET and using model files): [Example](https://github.com/go-jet/jet/wiki/UPDATE#example).  
I believe you are using non type-safe, and this form will probably be removed in next major version, because it can be replaced with type-safe SET or model files, which are safer and cleaner alternative.

**Comment by gkdr** [comment]
Thanks, that helped a lot.

I did miss that `UPDATE` has several forms. Is there a comment in the code somewhere that I did not see or is it only in the wiki? (Which I must admit I forgot to check :slightly_smiling_face: ) I should be able to do what I want using the `MODEL` approach.

I also missed that a `ProjectionList` is also a valid `Projection` itself and not just an alias for the slice.
