### ISSUE TITLE
Select returns empty data for custom models

### ISSUE THREAD

**Issue by ekundayo-ab** [go-jet/jet#74]
Hi nice job building this query builder 👍 

Currently when I try to use custom models, when executing the `SELECT` statement for postgres an empty data is returned. Example 👇 
```.go
db, err := config.GetDb()
defer db.Close()
if err != nil {
    return nil, err
}

var users = []User{} // User here is a custom model, not the one generated by jet

t := tbl.Users // Table generated for User by jet
stmt, _ := t.SELECT(t.AllColumns).FROM(t)
err = t.Query(db, &users)

fmt.Println(users) // Returns []
```

One reason for the custom model is: the table names are in **plural** but I want the model name to be **singular**, but jet generates the models as plurals just exactly from the db tables.

Is there a way I can write this to work explicitly with custom models instead of the ones generated by jet?

**Comment by go-jet** [comment]
Hi @ekundayo-ab ,
It is possible to use custom model files. Jet generates SQL projections in the form `table_name.column_name`. If there is some struct destination where `table_name` corresponds to type name and  `column_name` corresponds to field name, those fileds will be filled. Here you can find more [information](https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#custom-model-files).
In this case mapping, probably, does not work because of missing 's' in your model file.
Possible solutions are:
1) Alias table in the query:
```go
user := t.Users.As("user")
stmt := SELECT(user.AllColumns).FROM(user)       // projections will be user.name, user.age, etc...
```
2) Wrap auto generated types:
```go
type User struct {
    model.Users
}
...
user := []User{}
err := stmt.Query(db, &users)
```

**Comment by ekundayo-ab** [comment]
HI @go-jet Thanks a lot 👍 would try out your recommendations

**Comment by ekundayo-ab** [comment]
> Alias table in the query:
> user := t.Users.As("user")
> stmt := SELECT(user.AllColumns).FROM(user)       // projections will be 'user.name', 'user.age', etc...


Hi @go-jet your second recommendation works
